### ISSUE TITLE
Create basic slackbot

### ISSUE THREAD

**Issue by davilag** [bluetel/pr-police#2]
It has to run at a certain time (hardcoded) and send a message (hardcoded)

**Comment by hexnaught** [comment]
See #5 - Doesn't fill requirements to run at a certain time detailed in this ticket, not sure if we really need that right now? Not sure if we discussed an approach of how we want the app to work, is it going to be something always running? Is it going to be an app that is started and stopped as part of a cron job? 

Currently, running the app just sends a message to the URL in the env var.

I haven't added any checks for the URL. I just wanted to get something up in the repo to get the ball rolling, it is probably the most basic slackbot you can get.
